# Generated by Django 5.2.8 on 2025-11-17 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_message_citations_message_final_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrieved_chat_history', models.TextField(blank=True, null=True)),
                ('original_query', models.TextField()),
                ('rewritten_query', models.TextField(blank=True, null=True)),
                ('chat_history_summary', models.TextField(blank=True, null=True)),
                ('image_description', models.TextField(blank=True, null=True)),
                ('has_images', models.BooleanField(default=False)),
                ('ultimate_prompt', models.TextField(blank=True, null=True)),
                ('mcp_prompt', models.TextField(blank=True, null=True)),
                ('rag_prompt', models.TextField(blank=True, null=True)),
                ('mcp_output', models.JSONField(blank=True, default=dict)),
                ('rag_output', models.JSONField(blank=True, default=dict)),
                ('final_answer_before_polish', models.TextField(blank=True, null=True)),
                ('mcp_enabled', models.BooleanField(default=False)),
                ('rag_enabled', models.BooleanField(default=False)),
                ('yt_summary_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_execution', to='database.message')),
            ],
        ),
    ]
